services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  dbtest:
    build:
      context: .
      dockerfile: Dockerfile.db-test
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DOCKER_ENV: "true"
    volumes:
      - .:/app  # Монтируем весь проект
    working_dir: /app
volumes:
  pgdata: