FROM golang:1.24.4-alpine


WORKDIR /app

# Установка зависимостей
RUN apk add --no-cache git postgresql-client

# Копируем ВСЕ файлы проекта
COPY . .

# Устанавливаем рабочую директорию для тестов
WORKDIR /app/internal/db

# Запуск тестов
CMD ["go", "test", "-v", "./internal/db/..."]