version: '3.8'

services:
  # Основная БД
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Основной сервис (бэкенд + фронтенд)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: "postgres://test:test@postgres:5432/testdb?sslmode=disable"
      USE_KAFKA_STUB: "true"
    ports:
      - "8081:8080"  # Пробрасываем внутренний 8080 на внешний 8081
    volumes:
      - .:/app
    working_dir: /app

volumes:
  pgdata: